export const INTERNAL_SERVER_ERROR = "На сервере произошла ошибка.";
export const PROFILE_UPDATE_ERROR = "При обновлении профиля произошла ошибка.";
export const PROFILE_UPDATE_SUCCESS = "Данные успешно обновлены.";
export const LAPTOP_L_INIT_CARDS = 16;
export const LAPTOP_INIT_CARDS = 12;
export const TABLET_INIT_CARDS = 8;
export const MOBILE_INIT_CARDS = 5;
export const LAPTOP_L_MORE_CARDS = 4;
export const LAPTOP_MORE_CARDS = 3;
export const TABLET_MORE_CARDS = 2;
export const MOBILE_MORE_CARDS = 2;
export const LAPTOP_L_RESOLUTION = 1280;
export const LAPTOP_RESOLUTION = 990;
export const TABLET_RESOLUTION = 768;
export const SHORT_MOVIE = 40;
export const BEAT_FILMS_URL = "https://api.nomoreparties.co"
export const MAIN_URL = "https://api.diploma.kattrin.nomoredomainsrocks.ru"
export const CONFLICT_STATUS = 409
export const AUTH_STATUS = 401
export const INTERNAL_ERROR_STATUS = 500
export const CONFLICT_MESSAGE = "Пользователь с таким email уже существует."
export const REGISTRATION_ERROR = "При регистрации пользователя произошла ошибка."
export const LOGIN_ERROR = "При авторизации произошла ошибка. Токен не передан или передан не в том формате."
export const AUTH_ERROR = "Вы ввели неправильный логин или пароль."
export const EMAIL_REGEX = /^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,5}$/
export const SEARCH = "search"
export const IS_SHORT = "isShort"
export const MOVIES_LIST = "moviesList"
export const NETWORK_ERROR = "Во время запроса произошла ошибка. Возможно, проблема с соединением или сервер недоступен. Подождите немного и попробуйте ещё раз"
export const EMPTY_SEARCH = "Ничего не найдено"